// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdmalulbcqnothgxyrnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbWFsdWxiY3Fub3RoZ3h5cm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjYzMjksImV4cCI6MjA3MDg0MjMyOX0.5MraxDKUIpK6j8N9jV2l1TNdy4Ikx4V_lkwWDjtsAPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});